/*
 * Hashkey Exchange
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProductData {
    /// Product type (Token-Token, Token-Fiat, ST-Token)
    #[serde(rename = "productType", skip_serializing_if = "Option::is_none")]
    pub product_type: Option<String>,
    /// Buy maker fee currency
    #[serde(rename = "buyMakerFeeCurrency", skip_serializing_if = "Option::is_none")]
    pub buy_maker_fee_currency: Option<String>,
    /// Buy taker fee currency
    #[serde(rename = "buyTakerFeeCurrency", skip_serializing_if = "Option::is_none")]
    pub buy_taker_fee_currency: Option<String>,
    /// Sell maker fee currency
    #[serde(rename = "sellMakerFeeCurrency", skip_serializing_if = "Option::is_none")]
    pub sell_maker_fee_currency: Option<String>,
    /// Sell taker fee currency
    #[serde(rename = "sellTakerFeeCurrency", skip_serializing_if = "Option::is_none")]
    pub sell_taker_fee_currency: Option<String>,
    /// Maker fee including any discount
    #[serde(rename = "actualMakerRate", skip_serializing_if = "Option::is_none")]
    pub actual_maker_rate: Option<String>,
    /// Taker fee including any discount
    #[serde(rename = "actualTakerRate", skip_serializing_if = "Option::is_none")]
    pub actual_taker_rate: Option<String>,
    /// Update timestamp of the request (Daily snapshot)
    #[serde(rename = "updateTimeStamp", skip_serializing_if = "Option::is_none")]
    pub update_time_stamp: Option<i64>,
}

impl ProductData {
    pub fn new() -> ProductData {
        ProductData {
            product_type: None,
            buy_maker_fee_currency: None,
            buy_taker_fee_currency: None,
            sell_maker_fee_currency: None,
            sell_taker_fee_currency: None,
            actual_maker_rate: None,
            actual_taker_rate: None,
            update_time_stamp: None,
        }
    }
}

