/*
 * Bitget API
 *
 * Welcome to Bitget Developer document! 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SpotTradeCancelSymbolOrderPostRequest {
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
}

impl SpotTradeCancelSymbolOrderPostRequest {
    pub fn new() -> SpotTradeCancelSymbolOrderPostRequest {
        SpotTradeCancelSymbolOrderPostRequest {
            symbol: None,
        }
    }
}

