/*
 * Bitget API
 *
 * Welcome to Bitget Developer document! 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchOrderRequestInner {
    /// Unique identifier for the order.
    #[serde(rename = "orderId")]
    pub order_id: String,
    /// Custom order ID assigned by the client. Can be empty.
    #[serde(rename = "clientOid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub client_oid: Option<Option<String>>,
    /// Trading pair name, e.g., BTCUSDT.
    #[serde(rename = "symbol")]
    pub symbol: String,
    /// Price at which the order was placed.
    #[serde(rename = "price")]
    pub price: String,
    /// Amount of the order.
    #[serde(rename = "size")]
    pub size: String,
}

impl BatchOrderRequestInner {
    pub fn new(order_id: String, symbol: String, price: String, size: String) -> BatchOrderRequestInner {
        BatchOrderRequestInner {
            order_id,
            client_oid: None,
            symbol,
            price,
            size,
        }
    }
}

