/*
 * Bitget API
 *
 * Welcome to Bitget Developer document! 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContractConfigResponse {
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    #[serde(rename = "baseCoin", skip_serializing_if = "Option::is_none")]
    pub base_coin: Option<String>,
    #[serde(rename = "quoteCoin", skip_serializing_if = "Option::is_none")]
    pub quote_coin: Option<String>,
    #[serde(rename = "buyLimitPriceRatio", skip_serializing_if = "Option::is_none")]
    pub buy_limit_price_ratio: Option<String>,
    #[serde(rename = "sellLimitPriceRatio", skip_serializing_if = "Option::is_none")]
    pub sell_limit_price_ratio: Option<String>,
    #[serde(rename = "feeRateUpRatio", skip_serializing_if = "Option::is_none")]
    pub fee_rate_up_ratio: Option<String>,
    #[serde(rename = "makerFeeRate", skip_serializing_if = "Option::is_none")]
    pub maker_fee_rate: Option<String>,
    #[serde(rename = "takerFeeRate", skip_serializing_if = "Option::is_none")]
    pub taker_fee_rate: Option<String>,
    #[serde(rename = "openCostUpRatio", skip_serializing_if = "Option::is_none")]
    pub open_cost_up_ratio: Option<String>,
    #[serde(rename = "supportMarginCoins", skip_serializing_if = "Option::is_none")]
    pub support_margin_coins: Option<Vec<String>>,
    #[serde(rename = "minTradeNum", skip_serializing_if = "Option::is_none")]
    pub min_trade_num: Option<String>,
    #[serde(rename = "priceEndStep", skip_serializing_if = "Option::is_none")]
    pub price_end_step: Option<String>,
    #[serde(rename = "volumePlace", skip_serializing_if = "Option::is_none")]
    pub volume_place: Option<String>,
    #[serde(rename = "pricePlace", skip_serializing_if = "Option::is_none")]
    pub price_place: Option<String>,
    #[serde(rename = "sizeMultiplier", skip_serializing_if = "Option::is_none")]
    pub size_multiplier: Option<String>,
    #[serde(rename = "symbolType", skip_serializing_if = "Option::is_none")]
    pub symbol_type: Option<String>,
    #[serde(rename = "minTradeUSDT", skip_serializing_if = "Option::is_none")]
    pub min_trade_usdt: Option<String>,
    #[serde(rename = "maxSymbolOrderNum", skip_serializing_if = "Option::is_none")]
    pub max_symbol_order_num: Option<String>,
    #[serde(rename = "maxProductOrderNum", skip_serializing_if = "Option::is_none")]
    pub max_product_order_num: Option<String>,
    #[serde(rename = "maxPositionNum", skip_serializing_if = "Option::is_none")]
    pub max_position_num: Option<String>,
    #[serde(rename = "symbolStatus", skip_serializing_if = "Option::is_none")]
    pub symbol_status: Option<String>,
    #[serde(rename = "offTime", skip_serializing_if = "Option::is_none")]
    pub off_time: Option<String>,
    #[serde(rename = "limitOpenTime", skip_serializing_if = "Option::is_none")]
    pub limit_open_time: Option<String>,
    #[serde(rename = "deliveryTime", skip_serializing_if = "Option::is_none")]
    pub delivery_time: Option<String>,
    #[serde(rename = "deliveryStartTime", skip_serializing_if = "Option::is_none")]
    pub delivery_start_time: Option<String>,
    #[serde(rename = "launchTime", skip_serializing_if = "Option::is_none")]
    pub launch_time: Option<String>,
    #[serde(rename = "fundInterval", skip_serializing_if = "Option::is_none")]
    pub fund_interval: Option<String>,
    #[serde(rename = "minLever", skip_serializing_if = "Option::is_none")]
    pub min_lever: Option<String>,
    #[serde(rename = "maxLever", skip_serializing_if = "Option::is_none")]
    pub max_lever: Option<String>,
    #[serde(rename = "posLimit", skip_serializing_if = "Option::is_none")]
    pub pos_limit: Option<String>,
    #[serde(rename = "maintainTime", skip_serializing_if = "Option::is_none")]
    pub maintain_time: Option<String>,
}

impl ContractConfigResponse {
    pub fn new() -> ContractConfigResponse {
        ContractConfigResponse {
            symbol: None,
            base_coin: None,
            quote_coin: None,
            buy_limit_price_ratio: None,
            sell_limit_price_ratio: None,
            fee_rate_up_ratio: None,
            maker_fee_rate: None,
            taker_fee_rate: None,
            open_cost_up_ratio: None,
            support_margin_coins: None,
            min_trade_num: None,
            price_end_step: None,
            volume_place: None,
            price_place: None,
            size_multiplier: None,
            symbol_type: None,
            min_trade_usdt: None,
            max_symbol_order_num: None,
            max_product_order_num: None,
            max_position_num: None,
            symbol_status: None,
            off_time: None,
            limit_open_time: None,
            delivery_time: None,
            delivery_start_time: None,
            launch_time: None,
            fund_interval: None,
            min_lever: None,
            max_lever: None,
            pos_limit: None,
            maintain_time: None,
        }
    }
}

