/*
 * Bitget API
 *
 * Welcome to Bitget Developer document! 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DiscountResponseDiscountRateListInner {
    /// The tier of the discount rate
    #[serde(rename = "tier")]
    pub tier: String,
    /// The minimum amount for the discount rate tier
    #[serde(rename = "minAmount")]
    pub min_amount: String,
    /// The maximum amount for the discount rate tier
    #[serde(rename = "maxAmount")]
    pub max_amount: String,
    /// The discount rate for the given tier
    #[serde(rename = "discountRate")]
    pub discount_rate: String,
}

impl DiscountResponseDiscountRateListInner {
    pub fn new(tier: String, min_amount: String, max_amount: String, discount_rate: String) -> DiscountResponseDiscountRateListInner {
        DiscountResponseDiscountRateListInner {
            tier,
            min_amount,
            max_amount,
            discount_rate,
        }
    }
}

