/*
 * Bitget API
 *
 * Welcome to Bitget Developer document! 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FailureOrder {
    /// Unique identifier for the order that failed.
    #[serde(rename = "orderId")]
    pub order_id: String,
    /// Client-specified order ID.
    #[serde(rename = "clientOid")]
    pub client_oid: String,
    /// Error message explaining why the order failed.
    #[serde(rename = "errorMsg")]
    pub error_msg: String,
}

impl FailureOrder {
    pub fn new(order_id: String, client_oid: String, error_msg: String) -> FailureOrder {
        FailureOrder {
            order_id,
            client_oid,
            error_msg,
        }
    }
}

