/*
 * Bitget API
 *
 * Welcome to Bitget Developer document! 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FundingTimeResponse {
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    #[serde(rename = "nextFundingTime", skip_serializing_if = "Option::is_none")]
    pub next_funding_time: Option<String>,
    #[serde(rename = "ratePeriod", skip_serializing_if = "Option::is_none")]
    pub rate_period: Option<String>,
}

impl FundingTimeResponse {
    pub fn new() -> FundingTimeResponse {
        FundingTimeResponse {
            symbol: None,
            next_funding_time: None,
            rate_period: None,
        }
    }
}

