/*
 * Bitget API
 *
 * Welcome to Bitget Developer document! 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FutureAccountsResponse {
    #[serde(rename = "marginCoin", skip_serializing_if = "Option::is_none")]
    pub margin_coin: Option<String>,
    #[serde(rename = "locked", skip_serializing_if = "Option::is_none")]
    pub locked: Option<String>,
    #[serde(rename = "available", skip_serializing_if = "Option::is_none")]
    pub available: Option<String>,
    #[serde(rename = "crossedMaxAvailable", skip_serializing_if = "Option::is_none")]
    pub crossed_max_available: Option<String>,
    #[serde(rename = "isolatedMaxAvailable", skip_serializing_if = "Option::is_none")]
    pub isolated_max_available: Option<String>,
    #[serde(rename = "maxTransferOut", skip_serializing_if = "Option::is_none")]
    pub max_transfer_out: Option<String>,
    #[serde(rename = "accountEquity", skip_serializing_if = "Option::is_none")]
    pub account_equity: Option<String>,
    #[serde(rename = "usdtEquity", skip_serializing_if = "Option::is_none")]
    pub usdt_equity: Option<String>,
    #[serde(rename = "btcEquity", skip_serializing_if = "Option::is_none")]
    pub btc_equity: Option<String>,
    #[serde(rename = "crossedRiskRate", skip_serializing_if = "Option::is_none")]
    pub crossed_risk_rate: Option<String>,
    #[serde(rename = "unrealizedPL", skip_serializing_if = "Option::is_none")]
    pub unrealized_pl: Option<String>,
    #[serde(rename = "coupon", skip_serializing_if = "Option::is_none")]
    pub coupon: Option<String>,
    #[serde(rename = "unionTotalMagin", skip_serializing_if = "Option::is_none")]
    pub union_total_magin: Option<String>,
    #[serde(rename = "unionAvailable", skip_serializing_if = "Option::is_none")]
    pub union_available: Option<String>,
    #[serde(rename = "unionMm", skip_serializing_if = "Option::is_none")]
    pub union_mm: Option<String>,
    #[serde(rename = "assetList", skip_serializing_if = "Option::is_none")]
    pub asset_list: Option<Vec<models::FutureAccountsResponseAssetListInner>>,
}

impl FutureAccountsResponse {
    pub fn new() -> FutureAccountsResponse {
        FutureAccountsResponse {
            margin_coin: None,
            locked: None,
            available: None,
            crossed_max_available: None,
            isolated_max_available: None,
            max_transfer_out: None,
            account_equity: None,
            usdt_equity: None,
            btc_equity: None,
            crossed_risk_rate: None,
            unrealized_pl: None,
            coupon: None,
            union_total_magin: None,
            union_available: None,
            union_mm: None,
            asset_list: None,
        }
    }
}

