/*
 * Bitget API
 *
 * Welcome to Bitget Developer document! 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InterestResponseHistoryInterestRateListInner {
    /// Timestamp of the record (Unix millisecond timestamp)
    #[serde(rename = "ts")]
    pub ts: String,
    /// The annual interest rate for the given timestamp
    #[serde(rename = "annualInterestRate")]
    pub annual_interest_rate: String,
    /// The daily interest rate for the given timestamp
    #[serde(rename = "dailyInterestRate")]
    pub daily_interest_rate: String,
}

impl InterestResponseHistoryInterestRateListInner {
    pub fn new(ts: String, annual_interest_rate: String, daily_interest_rate: String) -> InterestResponseHistoryInterestRateListInner {
        InterestResponseHistoryInterestRateListInner {
            ts,
            annual_interest_rate,
            daily_interest_rate,
        }
    }
}

