/*
 * Bitwyre REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateOrdersCancelDeletePayloadParameter {
    #[serde(rename = "order_ids", skip_serializing_if = "Option::is_none")]
    pub order_ids: Option<Vec<String>>,
    #[serde(rename = "qtys", skip_serializing_if = "Option::is_none")]
    pub qtys: Option<Vec<i32>>,
}

impl PrivateOrdersCancelDeletePayloadParameter {
    pub fn new() -> PrivateOrdersCancelDeletePayloadParameter {
        PrivateOrdersCancelDeletePayloadParameter {
            order_ids: None,
            qtys: None,
        }
    }
}

