/*
 * Bitwyre REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateChatSearchGetPayloadParameter {
    #[serde(rename = "counterparty", skip_serializing_if = "Option::is_none")]
    pub counterparty: Option<String>,
    #[serde(rename = "keyword", skip_serializing_if = "Option::is_none")]
    pub keyword: Option<String>,
}

impl PrivateChatSearchGetPayloadParameter {
    pub fn new() -> PrivateChatSearchGetPayloadParameter {
        PrivateChatSearchGetPayloadParameter {
            counterparty: None,
            keyword: None,
        }
    }
}

