/*
 * Bitwyre REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BankDetailRequest {
    #[serde(rename = "bank_name", skip_serializing_if = "Option::is_none")]
    pub bank_name: Option<String>,
    #[serde(rename = "swift_code", skip_serializing_if = "Option::is_none")]
    pub swift_code: Option<String>,
    #[serde(rename = "bank_account", skip_serializing_if = "Option::is_none")]
    pub bank_account: Option<String>,
    #[serde(rename = "bank_account_name", skip_serializing_if = "Option::is_none")]
    pub bank_account_name: Option<String>,
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    #[serde(rename = "details", skip_serializing_if = "Option::is_none")]
    pub details: Option<String>,
    #[serde(rename = "account_nickname", skip_serializing_if = "Option::is_none")]
    pub account_nickname: Option<String>,
    #[serde(rename = "asset", skip_serializing_if = "Option::is_none")]
    pub asset: Option<String>,
}

impl BankDetailRequest {
    pub fn new() -> BankDetailRequest {
        BankDetailRequest {
            bank_name: None,
            swift_code: None,
            bank_account: None,
            bank_account_name: None,
            address: None,
            details: None,
            account_nickname: None,
            asset: None,
        }
    }
}

