/*
 * Bitwyre REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConvertStatus {
    #[serde(rename = "details", skip_serializing_if = "Option::is_none")]
    pub details: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "convert_uuid", skip_serializing_if = "Option::is_none")]
    pub convert_uuid: Option<uuid::Uuid>,
    #[serde(rename = "quote_asset", skip_serializing_if = "Option::is_none")]
    pub quote_asset: Option<String>,
    #[serde(rename = "quote_quantity", skip_serializing_if = "Option::is_none")]
    pub quote_quantity: Option<f32>,
    #[serde(rename = "base_asset", skip_serializing_if = "Option::is_none")]
    pub base_asset: Option<String>,
    #[serde(rename = "base_quantity", skip_serializing_if = "Option::is_none")]
    pub base_quantity: Option<f32>,
    #[serde(rename = "implied_convert_price", skip_serializing_if = "Option::is_none")]
    pub implied_convert_price: Option<f32>,
    #[serde(rename = "instrument", skip_serializing_if = "Option::is_none")]
    pub instrument: Option<String>,
}

impl ConvertStatus {
    pub fn new() -> ConvertStatus {
        ConvertStatus {
            details: None,
            status: None,
            convert_uuid: None,
            quote_asset: None,
            quote_quantity: None,
            base_asset: None,
            base_quantity: None,
            implied_convert_price: None,
            instrument: None,
        }
    }
}

