/*
 * Bitwyre REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FeeResponseValue {
    #[serde(rename = "global_fee", skip_serializing_if = "Option::is_none")]
    pub global_fee: Option<String>,
    #[serde(rename = "user_fee", skip_serializing_if = "Option::is_none")]
    pub user_fee: Option<String>,
}

impl FeeResponseValue {
    pub fn new() -> FeeResponseValue {
        FeeResponseValue {
            global_fee: None,
            user_fee: None,
        }
    }
}

