/*
 * Bitwyre REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FiatDataWithdrawalValue {
    #[serde(rename = "centralized_confirmation", skip_serializing_if = "Option::is_none")]
    pub centralized_confirmation: Option<i32>,
    #[serde(rename = "fee", skip_serializing_if = "Option::is_none")]
    pub fee: Option<String>,
    #[serde(rename = "gross_amount", skip_serializing_if = "Option::is_none")]
    pub gross_amount: Option<f32>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<uuid::Uuid>,
    #[serde(rename = "nett_amount", skip_serializing_if = "Option::is_none")]
    pub nett_amount: Option<String>,
    #[serde(rename = "provider", skip_serializing_if = "Option::is_none")]
    pub provider: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "submit_time", skip_serializing_if = "Option::is_none")]
    pub submit_time: Option<String>,
    #[serde(rename = "success_time", skip_serializing_if = "Option::is_none")]
    pub success_time: Option<i32>,
    #[serde(rename = "tx_id", skip_serializing_if = "Option::is_none")]
    pub tx_id: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "verification_uuid", skip_serializing_if = "Option::is_none")]
    pub verification_uuid: Option<uuid::Uuid>,
}

impl FiatDataWithdrawalValue {
    pub fn new() -> FiatDataWithdrawalValue {
        FiatDataWithdrawalValue {
            centralized_confirmation: None,
            fee: None,
            gross_amount: None,
            id: None,
            nett_amount: None,
            provider: None,
            status: None,
            submit_time: None,
            success_time: None,
            tx_id: None,
            r#type: None,
            verification_uuid: None,
        }
    }
}

