/*
 * Bitwyre REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KycRequest {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    #[serde(rename = "id_card_type", skip_serializing_if = "Option::is_none")]
    pub id_card_type: Option<i32>,
    #[serde(rename = "id_card_number", skip_serializing_if = "Option::is_none")]
    pub id_card_number: Option<String>,
    #[serde(rename = "id_card_country_code", skip_serializing_if = "Option::is_none")]
    pub id_card_country_code: Option<String>,
}

impl KycRequest {
    pub fn new() -> KycRequest {
        KycRequest {
            name: None,
            address: None,
            id_card_type: None,
            id_card_number: None,
            id_card_country_code: None,
        }
    }
}

