/*
 * Bitwyre REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LanguagesInner {
    #[serde(rename = "iso639-2_code", skip_serializing_if = "Option::is_none")]
    pub iso639_2_code: Option<String>,
    #[serde(rename = "language", skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
}

impl LanguagesInner {
    pub fn new() -> LanguagesInner {
        LanguagesInner {
            iso639_2_code: None,
            language: None,
        }
    }
}

