/*
 * Bitwyre REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VaultRequest {
    #[serde(rename = "asset", skip_serializing_if = "Option::is_none")]
    pub asset: Option<String>,
    #[serde(rename = "network_id", skip_serializing_if = "Option::is_none")]
    pub network_id: Option<String>,
    #[serde(rename = "convert_uuid", skip_serializing_if = "Option::is_none")]
    pub convert_uuid: Option<String>,
}

impl VaultRequest {
    pub fn new() -> VaultRequest {
        VaultRequest {
            asset: None,
            network_id: None,
            convert_uuid: None,
        }
    }
}

