/*
 * OKX API
 *
 * Welcome to OKX Developer document!   excluded below endpoints as they are if you need them please add and commit to https://github.com/kanekoshoyu/exchange-collection): - Trading Account (this might become needed, will add when we need it) - Block Trading - Financial Producer - Affiliate - Status - Announcement 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConvertorResponse {
    /// List of source currencies and their amounts
    #[serde(rename = "fromData")]
    pub from_data: Vec<models::ConvertorResponseFromDataInner>,
    /// List of target currency codes
    #[serde(rename = "toCcy")]
    pub to_ccy: Vec<String>,
}

impl ConvertorResponse {
    pub fn new(from_data: Vec<models::ConvertorResponseFromDataInner>, to_ccy: Vec<String>) -> ConvertorResponse {
        ConvertorResponse {
            from_data,
            to_ccy,
        }
    }
}

