/*
 * OKX API
 *
 * Welcome to OKX Developer document!   excluded below endpoints as they are if you need them please add and commit to https://github.com/kanekoshoyu/exchange-collection): - Trading Account (this might become needed, will add when we need it) - Block Trading - Financial Producer - Affiliate - Status - Announcement 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DebtRepayRequest {
    /// Debt currency type. Maximum 5 currencies can be selected in one order. Separate them with commas if multiple.
    #[serde(rename = "debtCcy")]
    pub debt_ccy: Vec<String>,
    /// Repay currency type. Only one receiving currency type can be selected and cannot be the same as the small payment currencies.
    #[serde(rename = "repayCcy")]
    pub repay_ccy: String,
}

impl DebtRepayRequest {
    pub fn new(debt_ccy: Vec<String>, repay_ccy: String) -> DebtRepayRequest {
        DebtRepayRequest {
            debt_ccy,
            repay_ccy,
        }
    }
}

