/*
 * OKX API
 *
 * Welcome to OKX Developer document!   excluded below endpoints as they are if you need them please add and commit to https://github.com/kanekoshoyu/exchange-collection): - Trading Account (this might become needed, will add when we need it) - Block Trading - Financial Producer - Affiliate - Status - Announcement 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LeadPlaceResponse {
    /// Order Tag
    #[serde(rename = "tag", skip_serializing_if = "Option::is_none")]
    pub tag: Option<String>,
    /// Lead or copy position ID
    #[serde(rename = "subPosId", skip_serializing_if = "Option::is_none")]
    pub sub_pos_id: Option<String>,
}

impl LeadPlaceResponse {
    pub fn new() -> LeadPlaceResponse {
        LeadPlaceResponse {
            tag: None,
            sub_pos_id: None,
        }
    }
}

