/*
 * OKX API
 *
 * Welcome to OKX Developer document!   excluded below endpoints as they are if you need them please add and commit to https://github.com/kanekoshoyu/exchange-collection): - Trading Account (this might become needed, will add when we need it) - Block Trading - Financial Producer - Affiliate - Status - Announcement 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LeadTradersResponseRanksInnerPnlRatiosInner {
    /// Begin time of P&L ratio on that day (timestamp format)
    #[serde(rename = "beginTs", skip_serializing_if = "Option::is_none")]
    pub begin_ts: Option<String>,
    /// P&L ratio for the day (e.g., 0.1 represents 10%)
    #[serde(rename = "pnlRatio", skip_serializing_if = "Option::is_none")]
    pub pnl_ratio: Option<String>,
}

impl LeadTradersResponseRanksInnerPnlRatiosInner {
    pub fn new() -> LeadTradersResponseRanksInnerPnlRatiosInner {
        LeadTradersResponseRanksInnerPnlRatiosInner {
            begin_ts: None,
            pnl_ratio: None,
        }
    }
}

