/*
 * OKX API
 *
 * Welcome to OKX Developer document!   excluded below endpoints as they are if you need them please add and commit to https://github.com/kanekoshoyu/exchange-collection): - Trading Account (this might become needed, will add when we need it) - Block Trading - Financial Producer - Affiliate - Status - Announcement 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MarginSignal {
    /// The unique identifier for the algorithm.
    #[serde(rename = "algoId")]
    pub algo_id: String,
    /// The type of margin adjustment. Possible values are: - \"add\": Add margin. - \"reduce\": Reduce margin. 
    #[serde(rename = "type")]
    pub r#type: String,
    /// The amount to adjust the margin balance.  Either `amt` or `percent` is required. 
    #[serde(rename = "amt")]
    pub amt: String,
    /// The percentage of margin adjustment. Either `amt` or `percent` is required. 
    #[serde(rename = "percent", skip_serializing_if = "Option::is_none")]
    pub percent: Option<String>,
    /// Whether to reinvest with the newly added margin. The default value is false. - `false`: Used as passive margin to prevent liquidation. - `true`: Added margin will be included in the total investment calculation and impact order size. 
    #[serde(rename = "allowReinvest", skip_serializing_if = "Option::is_none")]
    pub allow_reinvest: Option<bool>,
    /// The investment type, applicable when `allowReinvest` is true. It indicates the type of investment, such as \"percentage_investment\". 
    #[serde(rename = "investmentType", skip_serializing_if = "Option::is_none")]
    pub investment_type: Option<String>,
}

impl MarginSignal {
    pub fn new(algo_id: String, r#type: String, amt: String) -> MarginSignal {
        MarginSignal {
            algo_id,
            r#type,
            amt,
            percent: None,
            allow_reinvest: None,
            investment_type: None,
        }
    }
}

