/*
 * OKX API
 *
 * Welcome to OKX Developer document!   excluded below endpoints as they are if you need them please add and commit to https://github.com/kanekoshoyu/exchange-collection): - Trading Account (this might become needed, will add when we need it) - Block Trading - Financial Producer - Affiliate - Status - Announcement 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Vol24 {
    #[serde(rename = "volUSD", skip_serializing_if = "Option::is_none")]
    pub vol_usd: Option<String>,
    #[serde(rename = "colCNY", skip_serializing_if = "Option::is_none")]
    pub col_cny: Option<String>,
    #[serde(rename = "ts", skip_serializing_if = "Option::is_none")]
    pub ts: Option<String>,
}

impl Vol24 {
    pub fn new() -> Vol24 {
        Vol24 {
            vol_usd: None,
            col_cny: None,
            ts: None,
        }
    }
}

