/*
 * MEXC Crypto Exchange
 *
 * Welcome to mexc API document! 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CancelWithdraw200Response {
    /// The unique ID of the canceled withdrawal request.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

impl CancelWithdraw200Response {
    pub fn new() -> CancelWithdraw200Response {
        CancelWithdraw200Response {
            id: None,
        }
    }
}

