/*
 * MEXC Crypto Exchange
 *
 * Welcome to mexc API document! 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransferHistory {
    /// The transfer ID for the transaction.
    #[serde(rename = "tranId", skip_serializing_if = "Option::is_none")]
    pub tran_id: Option<String>,
    /// The account from which the transfer was initiated.
    #[serde(rename = "fromAccount", skip_serializing_if = "Option::is_none")]
    pub from_account: Option<String>,
    /// The account to which the transfer was made.
    #[serde(rename = "toAccount", skip_serializing_if = "Option::is_none")]
    pub to_account: Option<String>,
    /// The client-provided transaction ID.
    #[serde(rename = "clientTranId", skip_serializing_if = "Option::is_none")]
    pub client_tran_id: Option<String>,
    /// The asset being transferred.
    #[serde(rename = "asset", skip_serializing_if = "Option::is_none")]
    pub asset: Option<String>,
    /// The amount of the asset transferred.
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<String>,
    /// The type of account from which the transfer originated.
    #[serde(rename = "fromAccountType", skip_serializing_if = "Option::is_none")]
    pub from_account_type: Option<String>,
    /// The type of account to which the transfer was made.
    #[serde(rename = "toAccountType", skip_serializing_if = "Option::is_none")]
    pub to_account_type: Option<String>,
    /// The symbol of the asset in the from account.
    #[serde(rename = "fromSymbol", skip_serializing_if = "Option::is_none")]
    pub from_symbol: Option<String>,
    /// The symbol of the asset in the to account.
    #[serde(rename = "toSymbol", skip_serializing_if = "Option::is_none")]
    pub to_symbol: Option<String>,
    /// The status of the transfer (e.g., `COMPLETED`, `PENDING`).
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// The timestamp of the transfer in milliseconds since the epoch.
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<f64>,
}

impl TransferHistory {
    pub fn new() -> TransferHistory {
        TransferHistory {
            tran_id: None,
            from_account: None,
            to_account: None,
            client_tran_id: None,
            asset: None,
            amount: None,
            from_account_type: None,
            to_account_type: None,
            from_symbol: None,
            to_symbol: None,
            status: None,
            timestamp: None,
        }
    }
}

