/*
 * Coincheck Crypto Exchange
 *
 * Welcome to Coincheck API document! 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiBankAccountsIdDelete200Response {
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
}

impl ApiBankAccountsIdDelete200Response {
    pub fn new() -> ApiBankAccountsIdDelete200Response {
        ApiBankAccountsIdDelete200Response {
            success: None,
        }
    }
}

