/*
 * Coincheck Crypto Exchange
 *
 * Welcome to Coincheck API document! 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExchangeFeeValue {
    /// Maker fee rate for the specified pair.
    #[serde(rename = "maker_fee_rate", skip_serializing_if = "Option::is_none")]
    pub maker_fee_rate: Option<String>,
    /// Taker fee rate for the specified pair.
    #[serde(rename = "taker_fee_rate", skip_serializing_if = "Option::is_none")]
    pub taker_fee_rate: Option<String>,
}

impl ExchangeFeeValue {
    pub fn new() -> ExchangeFeeValue {
        ExchangeFeeValue {
            maker_fee_rate: None,
            taker_fee_rate: None,
        }
    }
}

