/*
 * Kraken API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DerivativesApiV3CancelorderPostRequest {
    /// The unique identifier of the order to be cancelled.
    #[serde(rename = "order_id", skip_serializing_if = "Option::is_none")]
    pub order_id: Option<String>,
    /// The client unique identifier of the order to be cancelled.
    #[serde(rename = "cliOrdId", skip_serializing_if = "Option::is_none")]
    pub cli_ord_id: Option<String>,
    /// The time before which the request should be processed; otherwise, it is rejected
    #[serde(rename = "processBefore", skip_serializing_if = "Option::is_none")]
    pub process_before: Option<String>,
}

impl DerivativesApiV3CancelorderPostRequest {
    pub fn new() -> DerivativesApiV3CancelorderPostRequest {
        DerivativesApiV3CancelorderPostRequest {
            order_id: None,
            cli_ord_id: None,
            process_before: None,
        }
    }
}

