/*
 * Kraken API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchOrderCancel {
    /// Unique client order identifier.
    #[serde(rename = "cliOrdId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub cli_ord_id: Option<Option<String>>,
    /// Order ID.
    #[serde(rename = "order_id", skip_serializing_if = "Option::is_none")]
    pub order_id: Option<uuid::Uuid>,
    /// Always cancel.
    #[serde(rename = "order", skip_serializing_if = "Option::is_none")]
    pub order: Option<Order>,
}

impl BatchOrderCancel {
    pub fn new() -> BatchOrderCancel {
        BatchOrderCancel {
            cli_ord_id: None,
            order_id: None,
            order: None,
        }
    }
}
/// Always cancel.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Order {
    #[serde(rename = "cancel")]
    Cancel,
}

impl Default for Order {
    fn default() -> Order {
        Self::Cancel
    }
}

