/*
 * Kraken API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MarginAccountTriggerEstimates : A structure containing the account's margin trigger estimates.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MarginAccountTriggerEstimates {
    /// The initial margin requirement of the account.
    #[serde(rename = "im", skip_serializing_if = "Option::is_none")]
    pub im: Option<f64>,
    /// The maintenance margin requirement of the account.
    #[serde(rename = "mm", skip_serializing_if = "Option::is_none")]
    pub mm: Option<f64>,
    /// The liquidation threshold of the account.
    #[serde(rename = "lt", skip_serializing_if = "Option::is_none")]
    pub lt: Option<f64>,
    /// The termination threshold of the account.
    #[serde(rename = "tt", skip_serializing_if = "Option::is_none")]
    pub tt: Option<f64>,
}

impl MarginAccountTriggerEstimates {
    /// A structure containing the account's margin trigger estimates.
    pub fn new() -> MarginAccountTriggerEstimates {
        MarginAccountTriggerEstimates {
            im: None,
            mm: None,
            lt: None,
            tt: None,
        }
    }
}

