/*
 * Kraken API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Mod1 {
    Mod1OneOf(Box<models::Mod1OneOf>),
    Mod1OneOf1(Box<models::Mod1OneOf1>),
    Mod1OneOf2(Box<models::Mod1OneOf2>),
}

impl Default for Mod1 {
    fn default() -> Self {
        Self::Mod1OneOf(Default::default())
    }
}

