/*
 * Kraken API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Rates {
    /// The absolute funding rate for the listed time period.
    #[serde(rename = "fundingRate", skip_serializing_if = "Option::is_none")]
    pub funding_rate: Option<f64>,
    /// The relative funding rate for the listed time period.
    #[serde(rename = "relativeFundingRate", skip_serializing_if = "Option::is_none")]
    pub relative_funding_rate: Option<f64>,
    /// The date and time UTC of the one-hour period to which the funding rate applies.
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
}

impl Rates {
    pub fn new() -> Rates {
        Rates {
            funding_rate: None,
            relative_funding_rate: None,
            timestamp: None,
        }
    }
}

