/*
 * Kraken API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransferRequest {
    /// The wallet (cash or margin account) from which funds should be debited
    #[serde(rename = "fromAccount")]
    pub from_account: String,
    /// The wallet (cash or margin account) to which funds should be credited
    #[serde(rename = "toAccount")]
    pub to_account: String,
    /// The currency unit to transfer
    #[serde(rename = "unit")]
    pub unit: String,
    /// The amount to transfer
    #[serde(rename = "amount")]
    pub amount: String,
}

impl TransferRequest {
    pub fn new(from_account: String, to_account: String, unit: String, amount: String) -> TransferRequest {
        TransferRequest {
            from_account,
            to_account,
            unit,
            amount,
        }
    }
}

